# Generated by Django 5.0.2 on 2024-03-01 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REST", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webcam",
            name="cars_count",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.IntegerField(), size=None
                ),
                size=None,
            ),
        ),
    ]
