# Generated by Django 5.0.2 on 2024-02-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REST", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crossroad",
            name="id",
        ),
        migrations.RemoveField(
            model_name="trafficlight",
            name="crossroad",
        ),
        migrations.RemoveField(
            model_name="webcam",
            name="crossroad",
        ),
        migrations.AlterField(
            model_name="crossroad",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
