# Generated by Django 5.0.2 on 2024-02-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REST", "0002_remove_crossroad_id_remove_trafficlight_crossroad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficlight",
            name="crossroad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="REST.crossroad",
            ),
        ),
        migrations.AddField(
            model_name="webcam",
            name="crossroad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="REST.crossroad",
            ),
        ),
    ]
