# Generated by Django 5.0.2 on 2024-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REST", "0002_street_crossroad"),
    ]

    operations = [
        migrations.AddField(
            model_name="streetcrossroad",
            name="index",
            field=models.IntegerField(default=0),
        ),
    ]
