# Generated by Django 5.0.2 on 2024-03-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REST", "0002_alter_webcam_cars_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webcam",
            name="cars_count",
            field=models.CharField(default="0,0,0,0", max_length=100),
        ),
    ]
