# Generated by Django 5.0.2 on 2024-03-20 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("REST", "0003_alter_webcam_cars_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trafficlight",
            old_name="green_probability",
            new_name="green_value",
        ),
    ]
