# Generated by Django 5.0.2 on 2024-03-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REST", "0004_rename_green_probability_trafficlight_green_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcam",
            name="last_send",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
