# Generated by Django 5.0.2 on 2024-03-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REST", "0005_webcam_last_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webcam",
            name="crossroad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="REST.crossroad",
                unique=True,
            ),
        ),
    ]
