# Generated by Django 5.0.2 on 2024-03-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REST", "0006_alter_webcam_crossroad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webcam",
            name="crossroad",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="REST.crossroad",
            ),
        ),
    ]
